"""Export all analytics data to static JSON files for the React frontend.

Bridges the Parquet data files and Python analytics functions to generate
JSON files consumed by the Next.js static frontend.

Usage:
    uv run python scripts/export_frontend_data.py
"""

import json
import logging
import math
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Make project root importable
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.config import INCEPTION_DATE, TOP_20_TICKERS, TOP_50_TICKERS
from src.data.storage import load_parquet
from src.proof.concentration import (
    build_mirror_index,
    compute_performance_metrics,
    compute_tracking_error,
    concentration_curve,
    variance_decomposition,
)

# Optional: SP-N Alpha NAV (generated by scripts/run_alpha_backtest.py)
_ALPHA_NAV_AVAILABLE = False

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Output directory
# ---------------------------------------------------------------------------
OUTPUT_DIR = PROJECT_ROOT / "frontend" / "public" / "data"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _clean_value(v: Any) -> Any:
    """Convert a single value to JSON-safe form.

    - NaN / Inf  ->  None  (becomes JSON null)
    - numpy scalars -> Python scalars
    - floats rounded to 6 decimal places
    - Timestamps / dates -> ISO-format strings
    """
    if isinstance(v, (np.integer,)):
        return int(v)
    if isinstance(v, (np.floating, float)):
        if math.isnan(v) or math.isinf(v):
            return None
        return round(float(v), 6)
    if isinstance(v, (np.bool_,)):
        return bool(v)
    if isinstance(v, (pd.Timestamp, datetime)):
        return v.isoformat()
    if isinstance(v, np.ndarray):
        return [_clean_value(x) for x in v.tolist()]
    return v


def _clean_dict(d: dict) -> dict:
    """Recursively clean a dict for JSON serialization."""
    cleaned = {}
    for k, v in d.items():
        if isinstance(v, dict):
            cleaned[k] = _clean_dict(v)
        elif isinstance(v, list):
            cleaned[k] = [_clean_value(x) if not isinstance(x, dict) else _clean_dict(x) for x in v]
        else:
            cleaned[k] = _clean_value(v)
    return cleaned


def _df_to_records(df: pd.DataFrame) -> list[dict]:
    """Convert DataFrame to a list of cleaned dicts."""
    records = df.to_dict(orient="records")
    return [_clean_dict(r) for r in records]


def _write_json(data: Any, filename: str) -> Path:
    """Write data to a JSON file in the output directory.

    Returns the path to the written file.
    """
    filepath = OUTPUT_DIR / filename
    with open(filepath, "w") as f:
        json.dump(data, f, indent=2, default=str)
    return filepath


def _file_size_str(path: Path) -> str:
    """Human-readable file size."""
    size = path.stat().st_size
    if size < 1024:
        return f"{size} B"
    elif size < 1024 * 1024:
        return f"{size / 1024:.1f} KB"
    else:
        return f"{size / (1024 * 1024):.1f} MB"


# ---------------------------------------------------------------------------
# Data loading (mirrors app/Home.py lines 54-77)
# ---------------------------------------------------------------------------

def load_all_data() -> tuple[pd.DataFrame, pd.Series]:
    """Load stock prices and benchmark from Parquet files.

    Returns:
        Tuple of (stock_prices DataFrame, benchmark Series).

    Raises:
        SystemExit: If required data files are empty or missing.
    """
    logger.info("Loading data from Parquet files...")

    prices_df = load_parquet("daily_prices")
    benchmark_df = load_parquet("benchmark_prices")

    if prices_df.empty:
        logger.error("daily_prices.parquet is empty or missing. Run backfill first.")
        sys.exit(1)

    if benchmark_df.empty:
        logger.error("benchmark_prices.parquet is empty or missing. Run backfill first.")
        sys.exit(1)

    # Parse dates
    prices_df["date"] = pd.to_datetime(prices_df["date"])

    # Handle both wide and long format
    if "symbol" in prices_df.columns:
        stock_prices = prices_df.pivot_table(
            index="date", columns="symbol", values="close"
        )
    else:
        stock_prices = prices_df.set_index("date")

    # Filter to known tickers and drop all-NaN rows
    stock_cols = [c for c in stock_prices.columns if c in TOP_50_TICKERS]
    stock_prices = stock_prices[stock_cols].dropna(how="all")

    # Benchmark
    benchmark_df["date"] = pd.to_datetime(benchmark_df["date"])
    benchmark = benchmark_df.set_index("date")["close"]
    benchmark.name = "sp500"

    logger.info(
        "Loaded %d trading days, %d tickers, benchmark range %s to %s",
        len(stock_prices),
        len(stock_cols),
        stock_prices.index.min().date(),
        stock_prices.index.max().date(),
    )

    return stock_prices, benchmark


# ---------------------------------------------------------------------------
# Exporters for each JSON file
# ---------------------------------------------------------------------------

def export_meta(
    stock_prices: pd.DataFrame,
    benchmark: pd.Series,
) -> Path:
    """Generate meta.json with dataset metadata."""
    logger.info("Generating meta.json...")

    start_date = stock_prices.index.min()
    end_date = stock_prices.index.max()
    available_top20 = [t for t in TOP_20_TICKERS if t in stock_prices.columns]

    meta = {
        "last_updated": str(end_date.date()),
        "inception_date": str(INCEPTION_DATE),
        "n_trading_days": len(stock_prices),
        "date_range": {
            "start": str(start_date.date()),
            "end": str(end_date.date()),
        },
        "top_20_tickers": available_top20,
        "top_50_tickers": [t for t in TOP_50_TICKERS if t in stock_prices.columns],
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }

    return _write_json(meta, "meta.json")


def export_concentration_curve(
    stock_returns: pd.DataFrame,
    benchmark_returns: pd.Series,
) -> Path:
    """Generate concentration_curve.json."""
    logger.info("Computing concentration curve...")

    curve = concentration_curve(stock_returns, benchmark_returns)

    if curve.empty:
        logger.warning("Concentration curve returned empty DataFrame")
        return _write_json({"curve": [], "r_squared_at_20": None}, "concentration_curve.json")

    # Extract R-squared at 20 stocks
    r2_at_20_rows = curve[curve["n_stocks"] == 20]["r_squared"]
    r2_at_20 = round(float(r2_at_20_rows.values[0]), 6) if len(r2_at_20_rows) > 0 else None

    payload = {
        "curve": _df_to_records(curve),
        "r_squared_at_20": r2_at_20,
    }

    return _write_json(payload, "concentration_curve.json")


def export_variance_decomposition(
    stock_returns: pd.DataFrame,
    benchmark_returns: pd.Series,
) -> Path:
    """Generate variance_decomposition.json."""
    logger.info("Computing variance decomposition...")

    var_decomp = variance_decomposition(stock_returns, benchmark_returns)

    if var_decomp.empty:
        logger.warning("Variance decomposition returned empty DataFrame")
        return _write_json({"decomposition": []}, "variance_decomposition.json")

    payload = {
        "decomposition": _df_to_records(var_decomp),
    }

    return _write_json(payload, "variance_decomposition.json")


def export_performance_nav(
    stock_prices: pd.DataFrame,
    benchmark: pd.Series,
    sp20_mirror: pd.DataFrame,
    sp20_equal: pd.DataFrame,
    benchmark_nav: pd.Series,
    mirror_nav: pd.Series,
    equal_nav: pd.Series,
    alpha_nav: pd.Series | None = None,
    hedged_nav: pd.Series | None = None,
    extra_navs: dict[str, pd.Series] | None = None,
) -> Path:
    """Generate performance_nav.json with weekly and recent daily NAV series."""
    logger.info("Building performance NAV data...")

    # --- Build combined NAV DataFrame (aligned on common dates) ---
    nav_dict: dict[str, pd.Series] = {
        "sp500": benchmark_nav,
        "sp20_mirror": mirror_nav,
        "sp20_equal": equal_nav,
    }
    if alpha_nav is not None:
        nav_dict["spn_alpha"] = alpha_nav
    if extra_navs:
        for key, series in extra_navs.items():
            if series is not None:
                nav_dict[key] = series
    if hedged_nav is not None:
        nav_dict["spn_hedged"] = hedged_nav

    all_navs = pd.DataFrame(nav_dict).dropna(how="all")
    nav_columns = list(nav_dict.keys())

    # Forward-fill small gaps, then drop any remaining NaN rows
    all_navs = all_navs.ffill().dropna()

    # --- Weekly downsample: take every 5th trading day ---
    weekly_indices = list(range(0, len(all_navs), 5))
    # Always include the last data point
    if weekly_indices[-1] != len(all_navs) - 1:
        weekly_indices.append(len(all_navs) - 1)
    weekly = all_navs.iloc[weekly_indices].copy()

    weekly_records = []
    for date_val, row in weekly.iterrows():
        record = {"date": str(date_val.date())}
        for col in nav_columns:
            record[col] = _clean_value(row[col])
        weekly_records.append(record)

    # --- Recent daily: last 252 trading days ---
    recent_n = min(252, len(all_navs))
    recent = all_navs.iloc[-recent_n:].copy()

    recent_records = []
    for date_val, row in recent.iterrows():
        record = {"date": str(date_val.date())}
        for col in nav_columns:
            record[col] = _clean_value(row[col])
        recent_records.append(record)

    payload = {
        "weekly": weekly_records,
        "recent_daily": recent_records,
        "n_total_days": len(all_navs),
        "n_weekly_points": len(weekly_records),
        "n_recent_daily_points": len(recent_records),
        "indices": nav_columns,
    }

    return _write_json(payload, "performance_nav.json")


def _compute_extra_metrics(
    nav: pd.Series,
    benchmark_nav: pd.Series | None = None,
) -> dict:
    """Compute additional daily-return metrics not in compute_performance_metrics.

    Returns dict with keys: beta, alpha, information_ratio, best_day,
    worst_day, win_rate, avg_daily_return.
    """
    daily_returns = nav.pct_change().dropna()

    best_day = float(daily_returns.max()) if len(daily_returns) > 0 else 0.0
    worst_day = float(daily_returns.min()) if len(daily_returns) > 0 else 0.0
    win_rate = float((daily_returns > 0).mean()) if len(daily_returns) > 0 else 0.0
    avg_daily_return = float(daily_returns.mean()) if len(daily_returns) > 0 else 0.0

    beta = 1.0
    alpha = 0.0
    information_ratio = 0.0

    if benchmark_nav is not None:
        bench_returns = benchmark_nav.pct_change().dropna()
        # Align on common index
        common = daily_returns.index.intersection(bench_returns.index)
        if len(common) > 10:
            dr = daily_returns.loc[common]
            br = bench_returns.loc[common]
            bench_var = br.var()
            if bench_var > 0:
                beta = float(dr.cov(br) / bench_var)
            excess = dr - br
            excess_mean = float(excess.mean())
            excess_std = float(excess.std())
            alpha = excess_mean * 252  # annualised
            if excess_std > 0:
                information_ratio = (excess_mean / excess_std) * (252 ** 0.5)

    return {
        "beta": round(beta, 6),
        "alpha": round(alpha, 6),
        "information_ratio": round(information_ratio, 6),
        "best_day": round(best_day, 6),
        "worst_day": round(worst_day, 6),
        "win_rate": round(win_rate, 6),
        "avg_daily_return": round(avg_daily_return, 8),
    }


def export_performance_metrics(
    mirror_nav: pd.Series,
    equal_nav: pd.Series,
    benchmark_nav: pd.Series,
    alpha_nav: pd.Series | None = None,
    hedged_nav: pd.Series | None = None,
    extra_navs: dict[str, pd.Series] | None = None,
) -> Path:
    """Generate performance_metrics.json for all indices."""
    logger.info("Computing performance metrics...")

    mirror_metrics = compute_performance_metrics(mirror_nav, benchmark_nav)
    equal_metrics = compute_performance_metrics(equal_nav, benchmark_nav)
    bench_metrics = compute_performance_metrics(benchmark_nav)

    # Enrich with extra daily-return metrics
    bench_extra = _compute_extra_metrics(benchmark_nav, None)
    mirror_extra = _compute_extra_metrics(mirror_nav, benchmark_nav)
    equal_extra = _compute_extra_metrics(equal_nav, benchmark_nav)

    bench_metrics.update(bench_extra)
    mirror_metrics.update(mirror_extra)
    equal_metrics.update(equal_extra)

    payload = {
        "sp500": _clean_dict(bench_metrics),
        "sp20_mirror": _clean_dict(mirror_metrics),
        "sp20_equal": _clean_dict(equal_metrics),
    }

    if alpha_nav is not None:
        alpha_metrics = compute_performance_metrics(alpha_nav, benchmark_nav)
        alpha_extra = _compute_extra_metrics(alpha_nav, benchmark_nav)
        alpha_metrics.update(alpha_extra)
        payload["spn_alpha"] = _clean_dict(alpha_metrics)

    if extra_navs:
        for key, series in extra_navs.items():
            if series is None or series.empty:
                continue
            extra_metrics = compute_performance_metrics(series, benchmark_nav)
            extra_extra = _compute_extra_metrics(series, benchmark_nav)
            extra_metrics.update(extra_extra)
            payload[key] = _clean_dict(extra_metrics)

    if hedged_nav is not None:
        hedged_metrics = compute_performance_metrics(hedged_nav, benchmark_nav)
        hedged_extra = _compute_extra_metrics(hedged_nav, benchmark_nav)
        hedged_metrics.update(hedged_extra)
        payload["spn_hedged"] = _clean_dict(hedged_metrics)

    return _write_json(payload, "performance_metrics.json")


def export_holdings(stock_prices: pd.DataFrame) -> Path:
    """Generate holdings.json with current top-20 holdings and weights."""
    logger.info("Computing current holdings...")

    # Company names and sectors for display
    COMPANY_NAMES: dict[str, str] = {
        "AAPL": "Apple Inc.", "MSFT": "Microsoft Corp.", "NVDA": "NVIDIA Corp.",
        "AMZN": "Amazon.com Inc.", "GOOGL": "Alphabet Inc.", "META": "Meta Platforms Inc.",
        "BRK-B": "Berkshire Hathaway Inc.", "LLY": "Eli Lilly and Co.",
        "AVGO": "Broadcom Inc.", "JPM": "JPMorgan Chase & Co.", "TSLA": "Tesla Inc.",
        "UNH": "UnitedHealth Group Inc.", "V": "Visa Inc.", "XOM": "Exxon Mobil Corp.",
        "MA": "Mastercard Inc.", "COST": "Costco Wholesale Corp.",
        "PG": "Procter & Gamble Co.", "HD": "The Home Depot Inc.",
        "JNJ": "Johnson & Johnson", "WMT": "Walmart Inc.",
        "NFLX": "Netflix Inc.", "CRM": "Salesforce Inc.", "BAC": "Bank of America Corp.",
        "ABBV": "AbbVie Inc.", "CVX": "Chevron Corp.", "MRK": "Merck & Co. Inc.",
        "KO": "The Coca-Cola Co.", "AMD": "Advanced Micro Devices Inc.",
        "PEP": "PepsiCo Inc.", "TMO": "Thermo Fisher Scientific Inc.",
    }
    SECTORS: dict[str, str] = {
        "AAPL": "Technology", "MSFT": "Technology", "NVDA": "Technology",
        "AMZN": "Consumer Discretionary", "GOOGL": "Communication Services",
        "META": "Communication Services", "BRK-B": "Financials",
        "LLY": "Health Care", "AVGO": "Technology", "JPM": "Financials",
        "TSLA": "Consumer Discretionary", "UNH": "Health Care",
        "V": "Financials", "XOM": "Energy", "MA": "Financials",
        "COST": "Consumer Staples", "PG": "Consumer Staples",
        "HD": "Consumer Discretionary", "JNJ": "Health Care",
        "WMT": "Consumer Staples", "NFLX": "Communication Services",
        "CRM": "Technology", "BAC": "Financials", "ABBV": "Health Care",
        "CVX": "Energy", "MRK": "Health Care", "KO": "Consumer Staples",
        "AMD": "Technology", "PEP": "Consumer Staples", "TMO": "Health Care",
    }

    available_top20 = [t for t in TOP_20_TICKERS if t in stock_prices.columns]
    last_prices = stock_prices[available_top20].iloc[-1]
    weights = last_prices / last_prices.sum()

    holdings = []
    for ticker in weights.sort_values(ascending=False).index:
        holdings.append({
            "ticker": ticker,
            "name": COMPANY_NAMES.get(ticker, ticker),
            "weight": _clean_value(weights[ticker]),
            "sector": SECTORS.get(ticker, ""),
            "last_price": _clean_value(last_prices[ticker]),
        })

    payload = {
        "as_of": str(stock_prices.index.max().date()),
        "n_holdings": len(holdings),
        "holdings": holdings,
    }

    return _write_json(payload, "holdings.json")


def export_drawdowns(
    benchmark_nav: pd.Series,
    mirror_nav: pd.Series,
    equal_nav: pd.Series,
    alpha_nav: pd.Series | None = None,
    hedged_nav: pd.Series | None = None,
    extra_navs: dict[str, pd.Series] | None = None,
) -> Path:
    """Generate drawdowns.json with weekly-downsampled drawdown series."""
    logger.info("Computing drawdown series...")

    # Compute drawdown from peak
    dd_dict: dict[str, pd.Series] = {
        "sp500": benchmark_nav / benchmark_nav.cummax() - 1,
        "sp20_mirror": mirror_nav / mirror_nav.cummax() - 1,
        "sp20_equal": equal_nav / equal_nav.cummax() - 1,
    }
    if alpha_nav is not None:
        dd_dict["spn_alpha"] = alpha_nav / alpha_nav.cummax() - 1
    if extra_navs:
        for key, series in extra_navs.items():
            if series is not None and not series.empty:
                dd_dict[key] = series / series.cummax() - 1
    if hedged_nav is not None:
        dd_dict["spn_hedged"] = hedged_nav / hedged_nav.cummax() - 1

    dd_columns = list(dd_dict.keys())

    # Align on common dates
    dd = pd.DataFrame(dd_dict).dropna(how="all").ffill().dropna()

    # Downsample to weekly (every 5th trading day)
    weekly_indices = list(range(0, len(dd), 5))
    if weekly_indices[-1] != len(dd) - 1:
        weekly_indices.append(len(dd) - 1)
    weekly_dd = dd.iloc[weekly_indices]

    records = []
    for date_val, row in weekly_dd.iterrows():
        record = {"date": str(date_val.date())}
        for col in dd_columns:
            record[col] = _clean_value(row[col])
        records.append(record)

    # Summary stats
    payload: dict[str, Any] = {
        "weekly": records,
        "n_points": len(records),
        "indices": dd_columns,
    }
    for col in dd_columns:
        payload[f"max_drawdown_{col}"] = _clean_value(dd[col].min())
        payload[f"max_drawdown_date_{col}"] = str(dd[col].idxmin().date())

    return _write_json(payload, "drawdowns.json")


# Company names and sectors for holdings display (shared across exporters)
_COMPANY_NAMES: dict[str, str] = {
    "AAPL": "Apple Inc.", "MSFT": "Microsoft Corp.", "NVDA": "NVIDIA Corp.",
    "AMZN": "Amazon.com Inc.", "GOOGL": "Alphabet Inc.", "META": "Meta Platforms Inc.",
    "BRK-B": "Berkshire Hathaway Inc.", "LLY": "Eli Lilly and Co.",
    "AVGO": "Broadcom Inc.", "JPM": "JPMorgan Chase & Co.", "TSLA": "Tesla Inc.",
    "UNH": "UnitedHealth Group Inc.", "V": "Visa Inc.", "XOM": "Exxon Mobil Corp.",
    "MA": "Mastercard Inc.", "COST": "Costco Wholesale Corp.",
    "PG": "Procter & Gamble Co.", "HD": "The Home Depot Inc.",
    "JNJ": "Johnson & Johnson", "WMT": "Walmart Inc.", "CASH": "Cash (Risk-Free)",
}
_SECTORS: dict[str, str] = {
    "AAPL": "Technology", "MSFT": "Technology", "NVDA": "Technology",
    "AMZN": "Consumer Discretionary", "GOOGL": "Communication Services",
    "META": "Communication Services", "BRK-B": "Financials",
    "LLY": "Health Care", "AVGO": "Technology", "JPM": "Financials",
    "TSLA": "Consumer Discretionary", "UNH": "Health Care",
    "V": "Financials", "XOM": "Energy", "MA": "Financials",
    "COST": "Consumer Staples", "PG": "Consumer Staples",
    "HD": "Consumer Discretionary", "JNJ": "Health Care",
    "WMT": "Consumer Staples", "CASH": "Cash",
}


def export_strategy_holdings(stock_prices: pd.DataFrame) -> Path:
    """Generate strategy_holdings.json with per-strategy portfolio weights.

    Each strategy (SP-N Alpha variants + SP-N Hedged) gets its own holdings
    list based on the final walk-forward training window's weights.  Falls
    back to market-cap weights if strategy_holdings.parquet is missing.
    """
    logger.info("Computing strategy holdings...")

    payload: dict[str, Any] = {
        "as_of": str(stock_prices.index.max().date()),
        "strategies": {},
    }

    try:
        raw = load_parquet("strategy_holdings")
        if raw.empty:
            raise ValueError("empty")

        last_prices = stock_prices.iloc[-1]

        # Group by strategy
        for strategy, group in raw.groupby("strategy"):
            sorted_group = group.sort_values("weight", ascending=False)
            holdings = []
            for rank, row in enumerate(sorted_group.itertuples(), start=1):
                ticker = row.ticker
                holdings.append({
                    "ticker": ticker,
                    "name": _COMPANY_NAMES.get(ticker, ticker),
                    "weight": _clean_value(row.weight),
                    "sector": _SECTORS.get(ticker, ""),
                    "last_price": _clean_value(
                        last_prices[ticker] if ticker in last_prices.index else None
                    ),
                    "rank": rank,
                })
            payload["strategies"][str(strategy)] = holdings

        logger.info("Exported holdings for %d strategies", len(payload["strategies"]))

    except Exception as e:
        logger.warning("No strategy holdings found — falling back to empty. %s", e)

    return _write_json(payload, "strategy_holdings.json")


def export_daily_deviations(
    sp20_mirror: pd.DataFrame,
    benchmark_returns: pd.Series,
) -> Path:
    """Generate daily_deviations.json with histogram of daily return differences."""
    logger.info("Computing daily deviation histogram...")

    # Extract mirror daily returns
    mirror_daily = sp20_mirror.set_index(
        pd.to_datetime(sp20_mirror["date"])
    )["daily_return"]

    # Align with benchmark returns on common dates
    common_idx = mirror_daily.index.intersection(benchmark_returns.index)
    mirror_aligned = mirror_daily.loc[common_idx].values
    bench_aligned = benchmark_returns.loc[common_idx].values

    # Compute deviations
    deviations = mirror_aligned - bench_aligned

    # Remove NaN values
    deviations = deviations[~np.isnan(deviations)]

    # Convert to percentage points for readability
    deviations_pct = deviations * 100.0

    # Compute histogram with numpy
    n_bins = 50
    counts, bin_edges = np.histogram(deviations_pct, bins=n_bins)

    # Build bin centers and records
    bins = []
    for i in range(len(counts)):
        bins.append({
            "bin_start": round(float(bin_edges[i]), 4),
            "bin_end": round(float(bin_edges[i + 1]), 4),
            "bin_center": round(float((bin_edges[i] + bin_edges[i + 1]) / 2), 4),
            "count": int(counts[i]),
        })

    # Summary statistics on the deviation (in percentage points)
    payload = {
        "bins": bins,
        "n_observations": int(len(deviations)),
        "unit": "percentage_points",
        "stats": {
            "mean": round(float(np.mean(deviations_pct)), 4),
            "std": round(float(np.std(deviations_pct)), 4),
            "median": round(float(np.median(deviations_pct)), 4),
            "min": round(float(np.min(deviations_pct)), 4),
            "max": round(float(np.max(deviations_pct)), 4),
            "skewness": round(float(pd.Series(deviations_pct).skew()), 4),
            "kurtosis": round(float(pd.Series(deviations_pct).kurtosis()), 4),
        },
    }

    return _write_json(payload, "daily_deviations.json")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    """Run all data exports and print a summary."""
    logger.info("=" * 60)
    logger.info("SP Index Lab -- Frontend Data Export")
    logger.info("=" * 60)

    # Ensure output directory exists
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    logger.info("Output directory: %s", OUTPUT_DIR)

    # ------------------------------------------------------------------
    # 1. Load raw data
    # ------------------------------------------------------------------
    stock_prices, benchmark = load_all_data()

    # ------------------------------------------------------------------
    # 2. Compute derived data (mirrors app/Home.py)
    # ------------------------------------------------------------------
    stock_returns = stock_prices.pct_change(fill_method=None).dropna(how="all")
    benchmark_returns = benchmark.pct_change().dropna()
    benchmark_nav = benchmark / benchmark.iloc[0]

    logger.info("Building SP-20 Mirror (cap-weighted)...")
    sp20_mirror = build_mirror_index(stock_prices, top_n=20, weighting="cap")

    logger.info("Building SP-20 Equal (equal-weighted)...")
    sp20_equal = build_mirror_index(stock_prices, top_n=20, weighting="equal")

    # Build NAV Series with DatetimeIndex for alignment
    mirror_nav = pd.Series(
        sp20_mirror["nav"].values,
        index=pd.to_datetime(sp20_mirror["date"]),
        name="sp20_mirror",
    )
    equal_nav = pd.Series(
        sp20_equal["nav"].values,
        index=pd.to_datetime(sp20_equal["date"]),
        name="sp20_equal",
    )

    # Load SP-N Alpha NAV if available (pre-computed by run_alpha_backtest.py)
    global _ALPHA_NAV_AVAILABLE
    alpha_nav = None
    try:
        alpha_df = load_parquet("alpha_nav")
        if not alpha_df.empty:
            alpha_df["date"] = pd.to_datetime(alpha_df["date"])
            alpha_nav = pd.Series(
                alpha_df["nav"].values,
                index=alpha_df["date"],
                name="spn_alpha",
            )
            _ALPHA_NAV_AVAILABLE = True
            logger.info("Loaded SP-N Alpha NAV (%d days)", len(alpha_nav))
    except Exception:
        logger.info("No SP-N Alpha NAV found — run scripts/run_alpha_backtest.py first")

    # Load SP-N Hedged NAV if available
    hedged_nav = None
    try:
        hedged_df = load_parquet("hedged_nav")
        if not hedged_df.empty:
            hedged_df["date"] = pd.to_datetime(hedged_df["date"])
            hedged_nav = pd.Series(
                hedged_df["nav"].values,
                index=hedged_df["date"],
                name="spn_hedged",
            )
            logger.info("Loaded SP-N Hedged NAV (%d days)", len(hedged_nav))
    except Exception:
        logger.info("No SP-N Hedged NAV found — run scripts/run_alpha_backtest.py first")

    # Load all SP-N Alpha variants (HRP, MVO Sharpe, MVO Min-Vol)
    # ml_ensemble is exposed as the canonical "spn_alpha"
    extra_navs: dict[str, pd.Series] = {}
    for variant in ("hrp", "mvo_sharpe", "mvo_minvol"):
        key = f"spn_alpha_{variant}"
        try:
            variant_df = load_parquet(f"alpha_nav_{variant}")
            if not variant_df.empty:
                variant_df["date"] = pd.to_datetime(variant_df["date"])
                extra_navs[key] = pd.Series(
                    variant_df["nav"].values,
                    index=variant_df["date"],
                    name=key,
                )
                logger.info("Loaded %s NAV (%d days)", key, len(extra_navs[key]))
        except Exception:
            logger.info("No %s NAV found", key)

    # ------------------------------------------------------------------
    # 3. Export each JSON file
    # ------------------------------------------------------------------
    written_files: list[Path] = []

    written_files.append(export_meta(stock_prices, benchmark))
    written_files.append(
        export_concentration_curve(stock_returns, benchmark_returns)
    )
    written_files.append(
        export_variance_decomposition(stock_returns, benchmark_returns)
    )
    written_files.append(
        export_performance_nav(
            stock_prices, benchmark,
            sp20_mirror, sp20_equal,
            benchmark_nav, mirror_nav, equal_nav,
            alpha_nav=alpha_nav, hedged_nav=hedged_nav,
            extra_navs=extra_navs,
        )
    )
    written_files.append(
        export_performance_metrics(
            mirror_nav, equal_nav, benchmark_nav,
            alpha_nav=alpha_nav, hedged_nav=hedged_nav,
            extra_navs=extra_navs,
        )
    )
    written_files.append(export_holdings(stock_prices))
    written_files.append(
        export_drawdowns(
            benchmark_nav, mirror_nav, equal_nav,
            alpha_nav=alpha_nav, hedged_nav=hedged_nav,
            extra_navs=extra_navs,
        )
    )
    written_files.append(export_strategy_holdings(stock_prices))
    written_files.append(
        export_daily_deviations(sp20_mirror, benchmark_returns)
    )

    # ------------------------------------------------------------------
    # 4. Print summary
    # ------------------------------------------------------------------
    logger.info("")
    logger.info("=" * 60)
    logger.info("Export complete. Files written:")
    logger.info("=" * 60)

    total_size = 0
    for fpath in written_files:
        size_str = _file_size_str(fpath)
        total_size += fpath.stat().st_size
        logger.info("  %-35s  %s", fpath.name, size_str)

    if total_size < 1024 * 1024:
        total_str = f"{total_size / 1024:.1f} KB"
    else:
        total_str = f"{total_size / (1024 * 1024):.1f} MB"

    logger.info("-" * 60)
    logger.info("  %-35s  %s", "TOTAL", total_str)
    logger.info("=" * 60)
    logger.info("Output directory: %s", OUTPUT_DIR)

    return 0


if __name__ == "__main__":
    sys.exit(main())
