"""Export all analytics data to static JSON files for the React frontend.

Bridges the Parquet data files and Python analytics functions to generate
JSON files consumed by the Next.js static frontend.

Usage:
    uv run python scripts/export_frontend_data.py
"""

import json
import logging
import math
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Make project root importable
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.config import (
    BENCHMARK_TICKER,
    CANDIDATE_POOL_TICKERS,
    DATA_DIR,
    INCEPTION_DATE,
    TRADING_DAYS_PER_YEAR,
)
from src.data.storage import load_parquet
from src.data.universe import (
    load_ranking_prices,
    load_shares_outstanding,
    make_universe_fn,
    rank_by_cap_proxy,
)
from src.proof.concentration import (
    build_mirror_index,
    compute_performance_metrics,
    concentration_curve,
    rolling_concentration,
)

# Optional: SP-N Alpha NAV (generated by scripts/run_alpha_backtest.py)
_ALPHA_NAV_AVAILABLE = False

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Output directory
# ---------------------------------------------------------------------------
OUTPUT_DIR = PROJECT_ROOT / "frontend" / "public" / "data"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _clean_value(v: Any) -> Any:
    """Convert a single value to JSON-safe form.

    - NaN / Inf  ->  None  (becomes JSON null)
    - numpy scalars -> Python scalars
    - floats rounded to 6 decimal places
    - Timestamps / dates -> ISO-format strings
    """
    if isinstance(v, (np.integer,)):
        return int(v)
    if isinstance(v, (np.floating, float)):
        if math.isnan(v) or math.isinf(v):
            return None
        return round(float(v), 6)
    if isinstance(v, (np.bool_,)):
        return bool(v)
    if isinstance(v, (pd.Timestamp, datetime)):
        return v.isoformat()
    if isinstance(v, np.ndarray):
        return [_clean_value(x) for x in v.tolist()]
    return v


def _clean_dict(d: dict) -> dict:
    """Recursively clean a dict for JSON serialization."""
    cleaned: dict[str, Any] = {}
    for k, v in d.items():
        if isinstance(v, dict):
            cleaned[k] = _clean_dict(v)
        elif isinstance(v, list):
            cleaned[k] = [_clean_value(x) if not isinstance(x, dict) else _clean_dict(x) for x in v]
        else:
            cleaned[k] = _clean_value(v)
    return cleaned


def _df_to_records(df: pd.DataFrame) -> list[dict]:
    """Convert DataFrame to a list of cleaned dicts."""
    records = df.to_dict(orient="records")
    return [_clean_dict(r) for r in records]


def _write_json(data: Any, filename: str) -> Path:
    """Write data to a JSON file in the output directory.

    Returns the path to the written file.
    """
    filepath = OUTPUT_DIR / filename
    with open(filepath, "w") as f:
        json.dump(data, f, indent=2, default=str)
    return filepath


def _file_size_str(path: Path) -> str:
    """Human-readable file size."""
    size = path.stat().st_size
    if size < 1024:
        return f"{size} B"
    elif size < 1024 * 1024:
        return f"{size / 1024:.1f} KB"
    else:
        return f"{size / (1024 * 1024):.1f} MB"


# ---------------------------------------------------------------------------
# Data loading (mirrors app/Home.py lines 54-77)
# ---------------------------------------------------------------------------

def load_all_data() -> tuple[pd.DataFrame, pd.Series]:
    """Load stock prices and benchmark from Parquet files.

    Returns:
        Tuple of (stock_prices DataFrame, benchmark Series).

    Raises:
        SystemExit: If required data files are empty or missing.
    """
    logger.info("Loading data from Parquet files...")

    prices_df = load_parquet("daily_prices")
    benchmark_df = load_parquet("benchmark_prices")

    if prices_df.empty:
        logger.error("daily_prices.parquet is empty or missing. Run backfill first.")
        sys.exit(1)

    if benchmark_df.empty:
        logger.error("benchmark_prices.parquet is empty or missing. Run backfill first.")
        sys.exit(1)

    # Parse dates
    prices_df["date"] = pd.to_datetime(prices_df["date"])

    # Handle both wide and long format
    if "symbol" in prices_df.columns:
        stock_prices = prices_df.pivot_table(
            index="date", columns="symbol", values="close"
        )
    else:
        stock_prices = prices_df.set_index("date")

    # Filter to the candidate pool and drop all-NaN rows
    stock_cols = [c for c in stock_prices.columns if c in CANDIDATE_POOL_TICKERS]
    stock_prices = stock_prices[stock_cols].dropna(how="all")

    # Benchmark (filter to the configured symbol — total-return index)
    if "symbol" in benchmark_df.columns:
        benchmark_df = benchmark_df[benchmark_df["symbol"] == BENCHMARK_TICKER]
    benchmark_df["date"] = pd.to_datetime(benchmark_df["date"])
    benchmark = benchmark_df.set_index("date")["close"]
    benchmark.name = "sp500"

    logger.info(
        "Loaded %d trading days, %d tickers, benchmark range %s to %s",
        len(stock_prices),
        len(stock_cols),
        stock_prices.index.min().date(),
        stock_prices.index.max().date(),
    )

    return stock_prices, benchmark


# ^IRX (13-week T-bill) is fetched but wasn't wired into Sharpe/Sortino/Jensen
# alpha — every headline used a static 4% instead of the realized rate, a
# ~15% swing on Sharpe over a period whose actual average was ~1.7%.
_FALLBACK_RISK_FREE_RATE = 0.04


def realized_risk_free_rate(start: pd.Timestamp, end: pd.Timestamp) -> float:
    """Mean realized ^IRX yield (annual, decimal) over [start, end].

    Falls back to ``_FALLBACK_RISK_FREE_RATE`` if market_indicators.parquet
    is missing/empty so a stale cache never blocks the export.
    """
    indicators = load_parquet("market_indicators")
    if indicators.empty or "risk_free" not in indicators.columns:
        logger.warning(
            "market_indicators.parquet missing 'risk_free' — falling back "
            "to a static %.1f%% risk-free rate.",
            _FALLBACK_RISK_FREE_RATE * 100,
        )
        return _FALLBACK_RISK_FREE_RATE

    indicators["date"] = pd.to_datetime(indicators["date"])
    window = indicators[(indicators["date"] >= start) & (indicators["date"] <= end)]
    rate_pct = window["risk_free"].dropna()
    if rate_pct.empty:
        return _FALLBACK_RISK_FREE_RATE

    # ^IRX quotes are annual percentage points (e.g. 3.668 == 3.668%).
    return float(rate_pct.mean()) / 100.0


# ---------------------------------------------------------------------------
# Exporters for each JSON file
# ---------------------------------------------------------------------------

def _load_research_block() -> dict[str, Any]:
    """Assemble the honest research-provenance block for meta.json.

    Combines the frozen dev-winner spec (race_result.json) with the
    one-shot holdout outcome (holdout_results.jsonl, latest) so the frontend
    can show the full picture — dev/holdout split, trial count, deflated
    Sharpe, and the pre-registered pass/fail — with no single crowned winner.
    Returns an empty dict if the research artefacts are absent.
    """
    research_dir = DATA_DIR / "research"
    block: dict[str, Any] = {}
    race_path = research_dir / "race_result.json"
    holdout_path = research_dir / "holdout_results.jsonl"

    if race_path.exists():
        race = json.loads(race_path.read_text())
        block["dev_winner_spec"] = {
            k: race[k] for k in ("engine", "n_policy", "overlay") if k in race
        }
        block["dev_trial_count"] = race.get("dev_trial_count")
        block["dev_end"] = race.get("dev_end")
    if holdout_path.exists():
        lines = [x for x in holdout_path.read_text().splitlines() if x.strip()]
        if lines:
            h = json.loads(lines[-1])
            block["holdout"] = {
                "window": h.get("holdout_window"),
                "passed": h.get("passed"),
                "checks": h.get("checks"),
                "deflated_sharpe": h.get("dev_deflated_sharpe"),
                "score": h.get("score"),
                "index_max_drawdown": h.get("index_max_drawdown"),
            }
            # The holdout record holds the FINAL dev trial count (after the
            # legacy re-race), which the frozen race_result predates.
            if h.get("dev_trial_count"):
                block["dev_trial_count"] = h["dev_trial_count"]
    block["retained_result"] = None  # shown side-by-side; no single headline
    return block


def export_meta(
    stock_prices: pd.DataFrame,
    benchmark: pd.Series,
    current_top50: list[str],
    headline: dict[str, Any],
) -> Path:
    """Generate meta.json with dataset metadata and headline stats.

    ``headline`` is the single source of truth for every number the
    frontend displays outside the charts (landing stats, counters) —
    components read it instead of hardcoding values that drift. The
    ``research`` block records the dev/holdout provenance so the site can
    present strategies honestly without crowning one.
    """
    logger.info("Generating meta.json...")

    display = stock_prices[stock_prices.index >= pd.Timestamp(INCEPTION_DATE)]
    start_date = display.index.min()
    end_date = display.index.max()

    meta = {
        "last_updated": str(end_date.date()),
        "inception_date": str(INCEPTION_DATE),
        "n_trading_days": len(display),
        "date_range": {
            "start": str(start_date.date()),
            "end": str(end_date.date()),
        },
        "benchmark": BENCHMARK_TICKER,
        "universe_method": "pit_membership_cap_proxy",
        "top_20_tickers": current_top50[:20],
        "top_50_tickers": current_top50,
        "headline": _clean_dict(headline),
        "research": _clean_dict(_load_research_block()),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }

    return _write_json(meta, "meta.json")


def export_concentration_curve(
    rolling: pd.DataFrame,
    stock_returns: pd.DataFrame,
    benchmark_returns: pd.Series,
    ranking_fn,
    window_days: int = 252,
) -> Path:
    """Generate concentration_curve.json from point-in-time rolling windows.

    The headline ``r_squared_at_20`` is the mean across rolling one-year
    windows of the OLS R² of benchmark returns on the top-20 *at each
    window's start* — no survivorship in the selection. The per-ticker
    cumulative curve shown in the UI is the latest window's.
    """
    logger.info("Computing concentration curve (PIT rolling windows)...")

    if rolling.empty:
        logger.warning("Rolling concentration returned empty DataFrame")
        return _write_json({"curve": [], "r_squared_at_20": None}, "concentration_curve.json")

    at20 = rolling[rolling["n_stocks"] == 20].sort_values("window_start")
    r2_at_20_mean = float(at20["r_squared"].mean())
    r2_at_20_latest = float(at20["r_squared"].iloc[-1])

    # Latest window's per-ticker cumulative curve (powers the UI).
    last_start = at20["window_start"].iloc[-1]
    window_returns = stock_returns.loc[stock_returns.index >= last_start].head(window_days)
    curve = concentration_curve(
        window_returns,
        benchmark_returns.loc[window_returns.index.min():window_returns.index.max()],
        ranked_tickers=ranking_fn(last_start),
    )

    windows = [
        {
            "window_start": str(row.window_start.date()),
            "window_end": str(row.window_end.date()),
            "r_squared_at_20": round(float(row.r_squared), 6),
        }
        for row in at20.itertuples()
    ]

    payload = {
        "curve": _df_to_records(curve),
        "r_squared_at_20": round(r2_at_20_mean, 6),
        "r_squared_at_20_latest": round(r2_at_20_latest, 6),
        "r_squared_windows": windows,
        "method": f"pit_rolling_ols_{window_days}d_step21d",
    }

    return _write_json(payload, "concentration_curve.json")


def export_variance_decomposition(rolling: pd.DataFrame) -> Path:
    """Generate variance_decomposition.json (mean R² by N across PIT windows)."""
    logger.info("Computing variance decomposition (PIT rolling mean)...")

    if rolling.empty:
        logger.warning("Rolling concentration returned empty DataFrame")
        return _write_json({"decomposition": []}, "variance_decomposition.json")

    summary = (
        rolling.groupby("n_stocks")["r_squared"]
        .agg(r_squared="mean", r_squared_min="min", r_squared_max="max")
        .reset_index()
    )

    payload = {
        "decomposition": _df_to_records(summary),
        "method": "pit_rolling_windows_mean",
    }

    return _write_json(payload, "variance_decomposition.json")


def export_performance_nav(
    stock_prices: pd.DataFrame,
    benchmark: pd.Series,
    sp20_mirror: pd.DataFrame,
    sp20_equal: pd.DataFrame,
    benchmark_nav: pd.Series,
    mirror_nav: pd.Series,
    equal_nav: pd.Series,
    alpha_nav: pd.Series | None = None,
) -> Path:
    """Generate performance_nav.json with weekly and recent daily NAV series."""
    logger.info("Building performance NAV data...")

    # --- Build combined NAV DataFrame (aligned on common dates) ---
    nav_dict: dict[str, pd.Series] = {
        "sp500": benchmark_nav,
        "sp20_mirror": mirror_nav,
        "sp20_equal": equal_nav,
    }
    if alpha_nav is not None:
        nav_dict["spn_alpha"] = alpha_nav

    all_navs = pd.DataFrame(nav_dict).dropna(how="all")
    nav_columns = list(nav_dict.keys())

    # Forward-fill interior gaps only. Truncate at the last date where EVERY
    # series still has real data — ffill past a series' end would fabricate
    # flat returns for a stale strategy (the frontend would chart performance
    # that never happened).
    last_real = min(s.last_valid_index() for s in nav_dict.values())
    all_navs = all_navs.loc[:last_real].ffill().dropna()

    # CRITICAL: re-normalise every series to $1 at the first common date.
    # Otherwise baselines (which start at inception 2014) appear visually
    # "ahead" of walk-forward strategies (which start 3 years later after
    # the training window), making comparison misleading.
    if not all_navs.empty:
        all_navs = all_navs.div(all_navs.iloc[0])

    # --- Weekly downsample: take every 5th trading day ---
    weekly_indices = list(range(0, len(all_navs), 5))
    # Always include the last data point
    if weekly_indices[-1] != len(all_navs) - 1:
        weekly_indices.append(len(all_navs) - 1)
    weekly = all_navs.iloc[weekly_indices].copy()

    weekly_records = []
    for date_val, row in weekly.iterrows():
        record = {"date": str(date_val.date())}
        for col in nav_columns:
            record[col] = _clean_value(row[col])
        weekly_records.append(record)

    # --- Recent daily: last 252 trading days ---
    recent_n = min(252, len(all_navs))
    recent = all_navs.iloc[-recent_n:].copy()

    recent_records = []
    for date_val, row in recent.iterrows():
        record = {"date": str(date_val.date())}
        for col in nav_columns:
            record[col] = _clean_value(row[col])
        recent_records.append(record)

    payload = {
        "weekly": weekly_records,
        "recent_daily": recent_records,
        "n_total_days": len(all_navs),
        "n_weekly_points": len(weekly_records),
        "n_recent_daily_points": len(recent_records),
        "indices": nav_columns,
    }

    return _write_json(payload, "performance_nav.json")


def _compute_extra_metrics(
    nav: pd.Series,
    benchmark_nav: pd.Series | None = None,
) -> dict:
    """Compute additional daily-return metrics not in compute_performance_metrics.

    Returns dict with keys: information_ratio, best_day, worst_day,
    win_rate, avg_daily_return. Deliberately does NOT return "alpha" or
    "beta" — compute_performance_metrics already provides Jensen's alpha
    and regression beta, and overriding alpha with annualised mean excess
    (as this function once did) silently changed its definition.
    """
    daily_returns = nav.pct_change().dropna()

    best_day = float(daily_returns.max()) if len(daily_returns) > 0 else 0.0
    worst_day = float(daily_returns.min()) if len(daily_returns) > 0 else 0.0
    win_rate = float((daily_returns > 0).mean()) if len(daily_returns) > 0 else 0.0
    avg_daily_return = float(daily_returns.mean()) if len(daily_returns) > 0 else 0.0

    information_ratio = 0.0

    if benchmark_nav is not None:
        bench_returns = benchmark_nav.pct_change().dropna()
        # Align on common index
        common = daily_returns.index.intersection(bench_returns.index)
        if len(common) > 10:
            excess = daily_returns.loc[common] - bench_returns.loc[common]
            excess_mean = float(excess.mean())
            excess_std = float(excess.std())
            if excess_std > 0:
                information_ratio = (excess_mean / excess_std) * (252 ** 0.5)

    return {
        "information_ratio": round(information_ratio, 6),
        "best_day": round(best_day, 6),
        "worst_day": round(worst_day, 6),
        "win_rate": round(win_rate, 6),
        "avg_daily_return": round(avg_daily_return, 8),
    }


def _window_info(nav: pd.Series) -> dict[str, Any]:
    """Describe a NAV series' window so the UI can label comparison bases."""
    return {
        "start": str(nav.index.min().date()),
        "end": str(nav.index.max().date()),
        "n_years": round(len(nav) / TRADING_DAYS_PER_YEAR, 2),
    }


def _cost_info(
    nav_gross: pd.Series | None,
    turnover: pd.Series | None,
    risk_free_rate: float = _FALLBACK_RISK_FREE_RATE,
) -> dict[str, Any]:
    """Gross-of-costs counterpart metrics (net is canonical everywhere)."""
    info: dict[str, Any] = {}
    if nav_gross is not None and len(nav_gross) > 1:
        gross = compute_performance_metrics(nav_gross, risk_free_rate=risk_free_rate)
        info["gross_cagr"] = gross.get("cagr")
        info["gross_sharpe"] = gross.get("sharpe_ratio")
    if turnover is not None and len(turnover) > 0 and nav_gross is not None:
        n_years = max(len(nav_gross) / TRADING_DAYS_PER_YEAR, 1e-9)
        info["annualized_turnover"] = float(turnover.sum()) / n_years
    return info


def export_performance_metrics(
    mirror_nav: pd.Series,
    equal_nav: pd.Series,
    benchmark_nav: pd.Series,
    alpha_nav: pd.Series | None = None,
    extras: dict[str, dict[str, Any]] | None = None,
    risk_free_rate: float = _FALLBACK_RISK_FREE_RATE,
) -> Path:
    """Generate performance_metrics.json for all indices.

    All strategy NAVs are net of transaction costs; per-strategy ``extras``
    carry the gross counterparts, turnover, and window descriptors.
    ``risk_free_rate`` should be the realized average ^IRX yield over the
    analysis window (see ``realized_risk_free_rate``), not a static guess —
    Sharpe/Sortino/Jensen alpha are all sensitive to this assumption.
    """
    logger.info("Computing performance metrics...")

    extras = extras or {}

    mirror_metrics = compute_performance_metrics(
        mirror_nav, benchmark_nav, risk_free_rate=risk_free_rate
    )
    equal_metrics = compute_performance_metrics(
        equal_nav, benchmark_nav, risk_free_rate=risk_free_rate
    )
    bench_metrics = compute_performance_metrics(
        benchmark_nav, risk_free_rate=risk_free_rate
    )

    # Enrich with extra daily-return metrics
    bench_metrics.update(_compute_extra_metrics(benchmark_nav, None))
    mirror_metrics.update(_compute_extra_metrics(mirror_nav, benchmark_nav))
    equal_metrics.update(_compute_extra_metrics(equal_nav, benchmark_nav))

    bench_metrics["window"] = _window_info(benchmark_nav)
    mirror_metrics["window"] = _window_info(mirror_nav)
    equal_metrics["window"] = _window_info(equal_nav)

    mirror_metrics.update(extras.get("sp20_mirror", {}))
    equal_metrics.update(extras.get("sp20_equal", {}))

    payload = {
        "sp500": _clean_dict(bench_metrics),
        "sp20_mirror": _clean_dict(mirror_metrics),
        "sp20_equal": _clean_dict(equal_metrics),
    }

    if alpha_nav is not None:
        alpha_metrics = compute_performance_metrics(
            alpha_nav, benchmark_nav, risk_free_rate=risk_free_rate
        )
        alpha_metrics.update(_compute_extra_metrics(alpha_nav, benchmark_nav))
        alpha_metrics["window"] = _window_info(alpha_nav)
        alpha_metrics.update(extras.get("spn_alpha", {}))
        payload["spn_alpha"] = _clean_dict(alpha_metrics)

    return _write_json(payload, "performance_metrics.json")


def export_holdings(stock_prices: pd.DataFrame, current_top20: list[str]) -> Path:
    """Generate holdings.json: current PIT top-20 with cap-proxy weights."""
    logger.info("Computing current holdings...")

    as_of = stock_prices.index.max()
    caps = rank_by_cap_proxy(load_ranking_prices(), load_shares_outstanding(), as_of)
    weights = caps.reindex(current_top20).dropna()
    weights = weights / weights.sum()
    last_prices = stock_prices.iloc[-1]

    holdings = []
    for ticker in weights.sort_values(ascending=False).index:
        holdings.append({
            "ticker": ticker,
            "name": _COMPANY_NAMES.get(ticker, ticker),
            "weight": _clean_value(weights[ticker]),
            "sector": _SECTORS.get(ticker, ""),
            "last_price": _clean_value(last_prices.get(ticker)),
        })

    payload = {
        "as_of": str(as_of.date()),
        "n_holdings": len(holdings),
        "holdings": holdings,
    }

    return _write_json(payload, "holdings.json")


def export_drawdowns(
    benchmark_nav: pd.Series,
    mirror_nav: pd.Series,
    equal_nav: pd.Series,
    alpha_nav: pd.Series | None = None,
) -> Path:
    """Generate drawdowns.json with weekly-downsampled drawdown series."""
    logger.info("Computing drawdown series...")

    # Compute drawdown from peak
    dd_dict: dict[str, pd.Series] = {
        "sp500": benchmark_nav / benchmark_nav.cummax() - 1,
        "sp20_mirror": mirror_nav / mirror_nav.cummax() - 1,
        "sp20_equal": equal_nav / equal_nav.cummax() - 1,
    }
    if alpha_nav is not None:
        dd_dict["spn_alpha"] = alpha_nav / alpha_nav.cummax() - 1

    dd_columns = list(dd_dict.keys())

    # Align on common dates; interior gaps only — truncate at the last date
    # where every series has real data (no fabricated flat tail).
    last_real = min(s.last_valid_index() for s in dd_dict.values())
    dd = pd.DataFrame(dd_dict).dropna(how="all").loc[:last_real].ffill().dropna()

    # Downsample to weekly (every 5th trading day)
    weekly_indices = list(range(0, len(dd), 5))
    if weekly_indices[-1] != len(dd) - 1:
        weekly_indices.append(len(dd) - 1)
    weekly_dd = dd.iloc[weekly_indices]

    records = []
    for date_val, row in weekly_dd.iterrows():
        record = {"date": str(date_val.date())}
        for col in dd_columns:
            record[col] = _clean_value(row[col])
        records.append(record)

    # Summary stats
    payload: dict[str, Any] = {
        "weekly": records,
        "n_points": len(records),
        "indices": dd_columns,
    }
    for col in dd_columns:
        payload[f"max_drawdown_{col}"] = _clean_value(dd[col].min())
        payload[f"max_drawdown_date_{col}"] = str(dd[col].idxmin().date())

    return _write_json(payload, "drawdowns.json")


# Company names and sectors for holdings display (covers the candidate pool)
_COMPANY_NAMES: dict[str, str] = {
    "AAPL": "Apple Inc.", "MSFT": "Microsoft Corp.", "NVDA": "NVIDIA Corp.",
    "AMZN": "Amazon.com Inc.", "GOOGL": "Alphabet Inc.", "META": "Meta Platforms Inc.",
    "BRK-B": "Berkshire Hathaway Inc.", "LLY": "Eli Lilly and Co.",
    "AVGO": "Broadcom Inc.", "JPM": "JPMorgan Chase & Co.", "TSLA": "Tesla Inc.",
    "UNH": "UnitedHealth Group Inc.", "V": "Visa Inc.", "XOM": "Exxon Mobil Corp.",
    "MA": "Mastercard Inc.", "COST": "Costco Wholesale Corp.",
    "PG": "Procter & Gamble Co.", "HD": "The Home Depot Inc.",
    "JNJ": "Johnson & Johnson", "WMT": "Walmart Inc.", "CASH": "Cash (Risk-Free)",
    "NFLX": "Netflix Inc.", "CRM": "Salesforce Inc.", "BAC": "Bank of America Corp.",
    "ABBV": "AbbVie Inc.", "CVX": "Chevron Corp.", "MRK": "Merck & Co. Inc.",
    "KO": "The Coca-Cola Co.", "AMD": "Advanced Micro Devices Inc.",
    "PEP": "PepsiCo Inc.", "TMO": "Thermo Fisher Scientific Inc.",
    "ORCL": "Oracle Corp.", "WFC": "Wells Fargo & Co.", "CSCO": "Cisco Systems Inc.",
    "ACN": "Accenture plc", "NOW": "ServiceNow Inc.", "ADBE": "Adobe Inc.",
    "LIN": "Linde plc", "IBM": "IBM Corp.", "MCD": "McDonald's Corp.",
    "PM": "Philip Morris International", "ABT": "Abbott Laboratories",
    "DIS": "The Walt Disney Co.", "ISRG": "Intuitive Surgical Inc.",
    "GE": "GE Aerospace", "TXN": "Texas Instruments Inc.", "INTU": "Intuit Inc.",
    "CAT": "Caterpillar Inc.", "QCOM": "Qualcomm Inc.", "AMGN": "Amgen Inc.",
    "PFE": "Pfizer Inc.", "BKNG": "Booking Holdings Inc.",
    "MU": "Micron Technology Inc.", "INTC": "Intel Corp.", "T": "AT&T Inc.",
    "VZ": "Verizon Communications", "C": "Citigroup Inc.", "GILD": "Gilead Sciences Inc.",
    "CMCSA": "Comcast Corp.", "BA": "The Boeing Co.", "SLB": "Schlumberger Ltd.",
    "MO": "Altria Group Inc.", "UNP": "Union Pacific Corp.", "MMM": "3M Co.",
    "HON": "Honeywell International", "AXP": "American Express Co.",
    "GS": "Goldman Sachs Group", "MS": "Morgan Stanley", "SCHW": "Charles Schwab Corp.",
    "BLK": "BlackRock Inc.", "NKE": "Nike Inc.", "UPS": "United Parcel Service",
    "USB": "U.S. Bancorp", "COP": "ConocoPhillips", "MDT": "Medtronic plc",
    "BMY": "Bristol-Myers Squibb", "CVS": "CVS Health Corp.", "LOW": "Lowe's Companies",
    "SBUX": "Starbucks Corp.", "TMUS": "T-Mobile US Inc.", "NEE": "NextEra Energy Inc.",
    "DHR": "Danaher Corp.", "ADP": "Automatic Data Processing",
    "AIG": "American International Group", "KHC": "The Kraft Heinz Co.",
    "F": "Ford Motor Co.", "GM": "General Motors Co.", "RTX": "RTX Corp.",
    "OXY": "Occidental Petroleum", "UBER": "Uber Technologies Inc.",
    "PLTR": "Palantir Technologies", "PYPL": "PayPal Holdings Inc.",
    "LMT": "Lockheed Martin Corp.", "CHTR": "Charter Communications",
    "AMT": "American Tower Corp.",
}
_SECTORS: dict[str, str] = {
    "AAPL": "Technology", "MSFT": "Technology", "NVDA": "Technology",
    "AMZN": "Consumer Discretionary", "GOOGL": "Communication Services",
    "META": "Communication Services", "BRK-B": "Financials",
    "LLY": "Health Care", "AVGO": "Technology", "JPM": "Financials",
    "TSLA": "Consumer Discretionary", "UNH": "Health Care",
    "V": "Financials", "XOM": "Energy", "MA": "Financials",
    "COST": "Consumer Staples", "PG": "Consumer Staples",
    "HD": "Consumer Discretionary", "JNJ": "Health Care",
    "WMT": "Consumer Staples", "CASH": "Cash",
    "NFLX": "Communication Services", "CRM": "Technology", "BAC": "Financials",
    "ABBV": "Health Care", "CVX": "Energy", "MRK": "Health Care",
    "KO": "Consumer Staples", "AMD": "Technology", "PEP": "Consumer Staples",
    "TMO": "Health Care", "ORCL": "Technology", "WFC": "Financials",
    "CSCO": "Technology", "ACN": "Technology", "NOW": "Technology",
    "ADBE": "Technology", "LIN": "Materials", "IBM": "Technology",
    "MCD": "Consumer Discretionary", "PM": "Consumer Staples",
    "ABT": "Health Care", "DIS": "Communication Services",
    "ISRG": "Health Care", "GE": "Industrials", "TXN": "Technology",
    "INTU": "Technology", "CAT": "Industrials", "QCOM": "Technology",
    "AMGN": "Health Care", "PFE": "Health Care", "BKNG": "Consumer Discretionary",
    "MU": "Technology", "INTC": "Technology", "T": "Communication Services",
    "VZ": "Communication Services", "C": "Financials", "GILD": "Health Care",
    "CMCSA": "Communication Services", "BA": "Industrials", "SLB": "Energy",
    "MO": "Consumer Staples", "UNP": "Industrials", "MMM": "Industrials",
    "HON": "Industrials", "AXP": "Financials", "GS": "Financials",
    "MS": "Financials", "SCHW": "Financials", "BLK": "Financials",
    "NKE": "Consumer Discretionary", "UPS": "Industrials", "USB": "Financials",
    "COP": "Energy", "MDT": "Health Care", "BMY": "Health Care",
    "CVS": "Health Care", "LOW": "Consumer Discretionary",
    "SBUX": "Consumer Discretionary", "TMUS": "Communication Services",
    "NEE": "Utilities", "DHR": "Health Care", "ADP": "Industrials",
    "AIG": "Financials", "KHC": "Consumer Staples", "F": "Consumer Discretionary",
    "GM": "Consumer Discretionary", "RTX": "Industrials", "OXY": "Energy",
    "UBER": "Industrials", "PLTR": "Technology", "PYPL": "Financials",
    "LMT": "Industrials", "CHTR": "Communication Services", "AMT": "Real Estate",
}


def export_strategy_holdings(stock_prices: pd.DataFrame) -> Path:
    """Generate strategy_holdings.json with retained strategy portfolio weights.

    The public site intentionally exposes only SP-N Alpha alongside the
    Mirror and Equal baselines. Older parquet files may still contain
    archived variants; those are ignored here.
    """
    logger.info("Computing strategy holdings...")

    payload: dict[str, Any] = {
        "as_of": str(stock_prices.index.max().date()),
        "strategies": {},
    }

    try:
        raw = load_parquet("strategy_holdings")
        if raw.empty:
            raise ValueError("empty")

        last_prices = stock_prices.iloc[-1]

        for strategy, group in raw.groupby("strategy"):
            if strategy != "spn_alpha":
                continue

            sorted_group = group.sort_values("weight", ascending=False)
            holdings = []
            for rank, row in enumerate(sorted_group.itertuples(), start=1):
                ticker = row.ticker
                holdings.append({
                    "ticker": ticker,
                    "name": _COMPANY_NAMES.get(ticker, ticker),
                    "weight": _clean_value(row.weight),
                    "sector": _SECTORS.get(ticker, ""),
                    "last_price": _clean_value(
                        last_prices[ticker] if ticker in last_prices.index else None
                    ),
                    "rank": rank,
                })
            payload["strategies"]["spn_alpha"] = holdings

        logger.info("Exported holdings for %d strategies", len(payload["strategies"]))

    except Exception as e:
        logger.warning("No strategy holdings found — falling back to empty. %s", e)

    return _write_json(payload, "strategy_holdings.json")


def export_daily_deviations(
    sp20_mirror: pd.DataFrame,
    benchmark_returns: pd.Series,
) -> Path:
    """Generate daily_deviations.json with histogram of daily return differences."""
    logger.info("Computing daily deviation histogram...")

    # Gross returns: deviations measure tracking (co-movement), so cost
    # drag on rebalance days is excluded from the histogram.
    mirror_daily = sp20_mirror.set_index(
        pd.to_datetime(sp20_mirror["date"])
    )["daily_return_gross"]

    # Align with benchmark returns on common dates
    common_idx = mirror_daily.index.intersection(benchmark_returns.index)
    mirror_aligned = mirror_daily.loc[common_idx].values
    bench_aligned = benchmark_returns.loc[common_idx].values

    # Compute deviations
    deviations = mirror_aligned - bench_aligned

    # Remove NaN values
    deviations = deviations[~np.isnan(deviations)]

    # Convert to percentage points for readability
    deviations_pct = deviations * 100.0

    # Compute histogram with numpy
    n_bins = 50
    counts, bin_edges = np.histogram(deviations_pct, bins=n_bins)

    # Build bin centers and records
    bins = []
    for i in range(len(counts)):
        bins.append({
            "bin_start": round(float(bin_edges[i]), 4),
            "bin_end": round(float(bin_edges[i + 1]), 4),
            "bin_center": round(float((bin_edges[i] + bin_edges[i + 1]) / 2), 4),
            "count": int(counts[i]),
        })

    # Summary statistics on the deviation (in percentage points)
    payload = {
        "bins": bins,
        "n_observations": int(len(deviations)),
        "unit": "percentage_points",
        "stats": {
            "mean": round(float(np.mean(deviations_pct)), 4),
            "std": round(float(np.std(deviations_pct)), 4),
            "median": round(float(np.median(deviations_pct)), 4),
            "min": round(float(np.min(deviations_pct)), 4),
            "max": round(float(np.max(deviations_pct)), 4),
            "skewness": round(float(pd.Series(deviations_pct).skew()), 4),
            "kurtosis": round(float(pd.Series(deviations_pct).kurtosis()), 4),
        },
    }

    return _write_json(payload, "daily_deviations.json")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    """Run all data exports and print a summary."""
    logger.info("=" * 60)
    logger.info("SP Index Lab -- Frontend Data Export")
    logger.info("=" * 60)

    # Ensure output directory exists
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    logger.info("Output directory: %s", OUTPUT_DIR)

    # ------------------------------------------------------------------
    # 1. Load raw data
    # ------------------------------------------------------------------
    stock_prices, benchmark = load_all_data()

    # ------------------------------------------------------------------
    # 2. Compute derived data — point-in-time universe throughout.
    # Data before INCEPTION_DATE exists only as ranking lookback.
    # ------------------------------------------------------------------
    inception = pd.Timestamp(INCEPTION_DATE)
    # Ranking uses the dividend-unadjusted panel (loaded inside universe/
    # mirror helpers); stock_prices stays the dividend-adjusted return basis.
    universe_fn = make_universe_fn(50)

    stock_returns = stock_prices.pct_change(fill_method=None).dropna(how="all")
    benchmark_display = benchmark[benchmark.index >= inception]
    benchmark_returns = benchmark_display.pct_change().dropna()
    benchmark_nav = benchmark_display / benchmark_display.iloc[0]

    # Realized ^IRX average over the analysis window — every Sharpe/Sortino/
    # Jensen-alpha below uses this instead of an assumed rate.
    risk_free_rate = realized_risk_free_rate(
        benchmark_display.index.min(), benchmark_display.index.max()
    )
    logger.info("Realized risk-free rate (^IRX mean): %.3f%%", risk_free_rate * 100)

    logger.info("Building SP-20 Mirror (cap-weighted)...")
    sp20_mirror = build_mirror_index(
        stock_prices, top_n=20, weighting="cap",
        universe_fn=universe_fn, start=inception,
    )

    logger.info("Building SP-20 Equal (equal-weighted)...")
    sp20_equal = build_mirror_index(
        stock_prices, top_n=20, weighting="equal",
        universe_fn=universe_fn, start=inception,
    )

    def _nav_series(df: pd.DataFrame, column: str, name: str) -> pd.Series:
        return pd.Series(df[column].values, index=pd.to_datetime(df["date"]), name=name)

    mirror_nav = _nav_series(sp20_mirror, "nav", "sp20_mirror")
    equal_nav = _nav_series(sp20_equal, "nav", "sp20_equal")

    # Load SP-N Alpha NAV (net + gross, pre-computed by run_alpha_backtest.py).
    global _ALPHA_NAV_AVAILABLE
    alpha_nav = None
    alpha_nav_gross = None
    try:
        alpha_df = load_parquet("alpha_nav")
        if not alpha_df.empty:
            alpha_df["date"] = pd.to_datetime(alpha_df["date"])
            alpha_nav = pd.Series(
                alpha_df["nav"].values, index=alpha_df["date"], name="spn_alpha"
            )
            if "nav_gross" in alpha_df.columns:
                alpha_nav_gross = pd.Series(
                    alpha_df["nav_gross"].values, index=alpha_df["date"]
                )
            _ALPHA_NAV_AVAILABLE = True
            logger.info("Loaded SP-N Alpha NAV (%d days)", len(alpha_nav))
        else:
            # load_parquet returns empty (with its own warning) when the file
            # doesn't exist yet — the expected state before the first
            # run_alpha_backtest.py run. Not an error.
            logger.info("No SP-N Alpha NAV found — run scripts/run_alpha_backtest.py first")
    except Exception:
        # alpha_nav.parquet EXISTS but failed to load (corrupt file, pyarrow
        # error, missing "nav"/"date" columns from a schema change). This is
        # a genuine regression, not the benign "not yet run" case above — it
        # must be loud, or meta.json silently ships without every alpha_*
        # headline key while the job still exits 0.
        logger.exception(
            "Failed to load SP-N Alpha NAV (alpha_nav.parquet exists but is "
            "unreadable) — shipping meta.json WITHOUT alpha_* headline keys."
        )

    # Rolling point-in-time concentration (windows start at inception)
    logger.info("Computing rolling PIT concentration windows...")
    rolling = rolling_concentration(
        stock_returns.loc[stock_returns.index >= inception],
        benchmark_returns,
        ranking_fn=universe_fn,
    )

    # Gross/turnover extras per strategy (net NAVs are canonical)
    extras: dict[str, dict[str, Any]] = {
        "sp20_mirror": _cost_info(
            _nav_series(sp20_mirror, "nav_gross", "g"),
            pd.Series(sp20_mirror["turnover"].values),
            risk_free_rate=risk_free_rate,
        ),
        "sp20_equal": _cost_info(
            _nav_series(sp20_equal, "nav_gross", "g"),
            pd.Series(sp20_equal["turnover"].values),
            risk_free_rate=risk_free_rate,
        ),
    }
    if alpha_nav_gross is not None:
        extras["spn_alpha"] = _cost_info(
            alpha_nav_gross, None, risk_free_rate=risk_free_rate
        )

    # Headline block: single source of truth for numbers shown in the UI.
    current_top50 = universe_fn(stock_prices.index[-1])
    at20 = rolling[rolling["n_stocks"] == 20]
    bench_m = compute_performance_metrics(benchmark_nav, risk_free_rate=risk_free_rate)
    mirror_m = compute_performance_metrics(
        mirror_nav, benchmark_nav, risk_free_rate=risk_free_rate
    )
    equal_m = compute_performance_metrics(
        equal_nav, benchmark_nav, risk_free_rate=risk_free_rate
    )
    headline: dict[str, Any] = {
        "r_squared_at_20": float(at20["r_squared"].mean()) if not at20.empty else None,
        "sp500_cagr": bench_m.get("cagr"),
        "mirror_cagr": mirror_m.get("cagr"),
        "mirror_alpha": mirror_m.get("alpha"),
        "equal_cagr": equal_m.get("cagr"),
        "equal_alpha": equal_m.get("alpha"),
        "net_of_costs": True,
    }
    if alpha_nav is not None:
        alpha_m = compute_performance_metrics(
            alpha_nav, benchmark_nav, risk_free_rate=risk_free_rate
        )
        headline.update({
            "alpha_cagr": alpha_m.get("cagr"),
            "alpha_sharpe": alpha_m.get("sharpe_ratio"),
            "alpha_jensen": alpha_m.get("alpha"),
            "alpha_max_drawdown": alpha_m.get("max_drawdown"),
        })

    # ------------------------------------------------------------------
    # 3. Export each JSON file
    # ------------------------------------------------------------------
    written_files: list[Path] = []

    written_files.append(
        export_meta(stock_prices, benchmark, current_top50, headline)
    )
    written_files.append(
        export_concentration_curve(
            rolling,
            stock_returns.loc[stock_returns.index >= inception],
            benchmark_returns,
            ranking_fn=universe_fn,
        )
    )
    written_files.append(export_variance_decomposition(rolling))
    written_files.append(
        export_performance_nav(
            stock_prices, benchmark_display,
            sp20_mirror, sp20_equal,
            benchmark_nav, mirror_nav, equal_nav,
            alpha_nav=alpha_nav,
        )
    )
    written_files.append(
        export_performance_metrics(
            mirror_nav, equal_nav, benchmark_nav,
            alpha_nav=alpha_nav,
            extras=extras,
            risk_free_rate=risk_free_rate,
        )
    )
    written_files.append(export_holdings(stock_prices, current_top50[:20]))
    written_files.append(
        export_drawdowns(
            benchmark_nav, mirror_nav, equal_nav,
            alpha_nav=alpha_nav,
        )
    )
    written_files.append(export_strategy_holdings(stock_prices))
    written_files.append(
        export_daily_deviations(sp20_mirror, benchmark_returns)
    )

    # ------------------------------------------------------------------
    # 4. Print summary
    # ------------------------------------------------------------------
    logger.info("")
    logger.info("=" * 60)
    logger.info("Export complete. Files written:")
    logger.info("=" * 60)

    total_size = 0
    for fpath in written_files:
        size_str = _file_size_str(fpath)
        total_size += fpath.stat().st_size
        logger.info("  %-35s  %s", fpath.name, size_str)

    if total_size < 1024 * 1024:
        total_str = f"{total_size / 1024:.1f} KB"
    else:
        total_str = f"{total_size / (1024 * 1024):.1f} MB"

    logger.info("-" * 60)
    logger.info("  %-35s  %s", "TOTAL", total_str)
    logger.info("=" * 60)
    logger.info("Output directory: %s", OUTPUT_DIR)

    return 0


if __name__ == "__main__":
    sys.exit(main())
