"use client";

import { motion, type Variants } from "framer-motion";

import { useLabDataSlice, transformMeta } from "@/hooks/useLabData";

/* ================================================================
   StatsPreview
   Three metric preview cards displayed in a horizontal row.
   Values come from /data/meta.json's headline block (regenerated by
   the daily pipeline) — never hardcode numbers here.
   ================================================================ */

const containerVariants: Variants = {
  hidden: {},
  visible: {
    transition: {
      staggerChildren: 0.2,
      delayChildren: 0.6,
    },
  },
};

const cardVariants: Variants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.6, ease: "easeOut" as const },
  },
};

const formatPct = (v: number | undefined, signed = false): string => {
  if (v === undefined || v === null) return "—";
  const pct = (v * 100).toFixed(1);
  return signed && v >= 0 ? `+${pct}%` : `${pct}%`;
};

export default function StatsPreview() {
  const { data: rawMeta } = useLabDataSlice<Record<string, unknown>>("meta");
  const headline = rawMeta ? transformMeta(rawMeta).headline : undefined;

  const stats = [
    {
      value: formatPct(headline?.rSquaredAt20),
      label: "Avg R-squared at 20 stocks",
    },
    {
      value: formatPct(headline?.alphaCagr),
      label: "SP-N Alpha CAGR (net of costs)",
    },
    {
      value: formatPct(headline?.alphaJensen, true),
      label: "SP-N Alpha Jensen alpha (net)",
    },
  ];

  return (
    <motion.div
      className="flex w-full flex-col items-center justify-center gap-4 px-4 sm:flex-row sm:gap-8"
      variants={containerVariants}
      initial="hidden"
      animate="visible"
    >
      {stats.map((stat) => (
        <motion.div
          key={stat.label}
          className="group w-full rounded-xl border border-[#1A1A24] bg-bg-secondary px-8 py-6 transition-colors duration-300 hover:border-accent-primary/30 sm:w-auto"
          variants={cardVariants}
        >
          <p className="text-3xl font-bold text-accent-primary md:text-4xl">
            {stat.value}
          </p>
          <p className="mt-1 text-sm text-text-secondary">{stat.label}</p>
        </motion.div>
      ))}
    </motion.div>
  );
}
