"use client";

import { useLabDataSlice, transformMeta } from "@/hooks/useLabData";

/* ================================================================
   StatsPreview
   Three key facts, factsheet style. Values come from
   /data/meta.json (regenerated by the daily pipeline) — never
   hardcode numbers here.

   These deliberately do NOT lead with SP-N Alpha's return. Three
   tiles all promoting one strategy's full-sample figures is what
   made the old landing page contradict its own holdout result two
   screens later. What is shown instead is the claim that actually
   holds (the replication R-squared) and the two disclosures that
   qualify everything else.

   No entrance animation: the previous version delayed 0.6s and
   then staggered, so the figures were absent for over a second on
   a page whose whole job is to state them.
   ================================================================ */

const formatPct = (v: number | undefined): string => {
  if (v === undefined || v === null) return "—";
  return `${(v * 100).toFixed(1)}%`;
};

export default function StatsPreview() {
  const { data: rawMeta } = useLabDataSlice<Record<string, unknown>>("meta");
  const meta = rawMeta ? transformMeta(rawMeta) : undefined;
  const headline = meta?.headline;
  const research = meta?.research;

  const checks = research?.checks;
  const checksMet = checks
    ? [
        checks.beatSp500CagrAndSharpe,
        checks.beatEqualCagrAndSharpe,
        checks.maxDrawdownWithinMultiple,
      ].filter(Boolean).length
    : undefined;

  const stats: { value: string; label: string; note?: string }[] = [
    {
      value: formatPct(headline?.rSquaredAt20),
      label: "Mean R-squared at 20 stocks",
      note: "Rolling 1-year windows, point-in-time top 20",
    },
    {
      value: checksMet === undefined ? "—" : `${checksMet} of 3`,
      label: "Pre-registered holdout checks met",
      note: "Criteria committed before the holdout was touched",
    },
    {
      value: research?.devTrialCount ? `${research.devTrialCount}` : "—",
      label: "Development trials logged",
      note:
        research?.deflatedSharpe !== undefined
          ? `Deflated Sharpe ${research.deflatedSharpe.toFixed(2)}`
          : undefined,
    },
  ];

  return (
    <dl className="grid gap-px border bg-border sm:grid-cols-3">
      {stats.map((stat) => (
        <div key={stat.label} className="bg-ground px-5 py-4">
          <dd className="num text-3xl font-normal tracking-tight text-ink">
            {stat.value}
          </dd>
          <dt className="mt-1.5 text-sm text-ink-secondary">{stat.label}</dt>
          {stat.note && (
            <p className="mt-1 text-xs text-ink-muted">{stat.note}</p>
          )}
        </div>
      ))}
    </dl>
  );
}
